// <auto-generated />
namespace PGD.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddColunaIdModalidadeTbProduto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddColunaIdModalidadeTbProduto));
        
        string IMigrationMetadata.Id
        {
            get { return "202110261441429_AddColunaIdModalidadeTbProduto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
