//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGD.Infra.CrossCutting.Util.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PGD.Infra.CrossCutting.Util.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [PGD] O plano de trabalho PGD {0} do servidor {1} foi alterado e requer assinatura.
        /// </summary>
        public static string ASSUNTO_EMAIL_NOTIFICACAO_ALTERACAO_PACTO {
            get {
                return ResourceManager.GetString("ASSUNTO_EMAIL_NOTIFICACAO_ALTERACAO_PACTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [PGD] O plano de trabalho PGD {0} do servidor {1} foi assinado pela chefia.
        /// </summary>
        public static string ASSUNTO_EMAIL_NOTIFICACAO_ASSINATURA_PACTO_PELA_CHEFIA {
            get {
                return ResourceManager.GetString("ASSUNTO_EMAIL_NOTIFICACAO_ASSINATURA_PACTO_PELA_CHEFIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [PGD] O plano de trabalho PGD {0} do servidor {1} foi avaliado por {2}..
        /// </summary>
        public static string ASSUNTO_EMAIL_NOTIFICACAO_AVALIACAO_PACTO_PELA_CHEFIA {
            get {
                return ResourceManager.GetString("ASSUNTO_EMAIL_NOTIFICACAO_AVALIACAO_PACTO_PELA_CHEFIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [PGD] O plano de trabalho PGD {0} do servidor {1} foi avaliado parcialmente por {2}..
        /// </summary>
        public static string ASSUNTO_EMAIL_NOTIFICACAO_AVALIACAO_PARCIAL_PACTO_PELA_CHEFIA {
            get {
                return ResourceManager.GetString("ASSUNTO_EMAIL_NOTIFICACAO_AVALIACAO_PARCIAL_PACTO_PELA_CHEFIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [PGD] O plano de trabalho PGD {0} do servidor {1} encerrou e requer avaliação.
        /// </summary>
        public static string ASSUNTO_EMAIL_NOTIFICACAO_FIM_PACTO {
            get {
                return ResourceManager.GetString("ASSUNTO_EMAIL_NOTIFICACAO_FIM_PACTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [PGD] O servidor {0} criou novo plano de trabalho PGD {1}.
        /// </summary>
        public static string ASSUNTO_EMAIL_NOTIFICACAO_INCLUSAO_PACTO {
            get {
                return ResourceManager.GetString("ASSUNTO_EMAIL_NOTIFICACAO_INCLUSAO_PACTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [PGD] O chefe {0} criou novo plano de trabalho PGD {1} para o servidor {2}.
        /// </summary>
        public static string ASSUNTO_EMAIL_NOTIFICACAO_INCLUSAO_PACTO_PELA_CHEFIA {
            get {
                return ResourceManager.GetString("ASSUNTO_EMAIL_NOTIFICACAO_INCLUSAO_PACTO_PELA_CHEFIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [PGD] O plano de trabalho PGD {0} do servidor {1} foi interrompido por {2}..
        /// </summary>
        public static string ASSUNTO_EMAIL_NOTIFICACAO_INTERRUPCAO_PACTO {
            get {
                return ResourceManager.GetString("ASSUNTO_EMAIL_NOTIFICACAO_INTERRUPCAO_PACTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [PGD] O plano de trabalho PGD {0} do servidor {1} foi reativado por {2}..
        /// </summary>
        public static string ASSUNTO_EMAIL_NOTIFICACAO_PACTO_REINICIADO_APOS_SUSPENSAO {
            get {
                return ResourceManager.GetString("ASSUNTO_EMAIL_NOTIFICACAO_PACTO_REINICIADO_APOS_SUSPENSAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [PGD] O plano de trabalho PGD {0} do servidor {1} foi reativado automaticamente pelo sistema..
        /// </summary>
        public static string ASSUNTO_EMAIL_NOTIFICACAO_PACTO_REINICIADO_AUTOMATICAMENTE {
            get {
                return ResourceManager.GetString("ASSUNTO_EMAIL_NOTIFICACAO_PACTO_REINICIADO_AUTOMATICAMENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [PGD] O plano de trabalho PGD {0} do servidor {1} foi suspenso por {2}..
        /// </summary>
        public static string ASSUNTO_EMAIL_NOTIFICACAO_SUSPENSAO_PACTO {
            get {
                return ResourceManager.GetString("ASSUNTO_EMAIL_NOTIFICACAO_SUSPENSAO_PACTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;b&gt;NOTIFICAÇÃO DO SISTEMA PGD&lt;/b&gt;
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///O plano de trabalho PGD {0} do servidor {1} foi alterado e requer assinaturas.
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Período do plano de trabalho: {2} a {3}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Atividades:
        ///{4}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///O plano de trabalho deve ser assinado pelo servidor e chefia antes de seu início.
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Para acessar o plano de trabalho clique {5}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Obrigado!
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Sistema PGD.
        /// </summary>
        public static string CORPO_EMAIL_NOTIFICACAO_ALTERACAO_PACTO {
            get {
                return ResourceManager.GetString("CORPO_EMAIL_NOTIFICACAO_ALTERACAO_PACTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;b&gt;NOTIFICAÇÃO DO SISTEMA PGD&lt;/b&gt;
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///O plano de trabalho PGD {0} do servidor {1} foi alterado pela chefia, conforme dados abaixo:
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Período do plano de trabalho: {2} a {3}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Atividades:
        ///{4}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Para acessar o plano de trabalho clique {5}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Obrigado!
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Sistema PGD.
        /// </summary>
        public static string CORPO_EMAIL_NOTIFICACAO_ALTERACAO_PACTO_EM_ANDAMENTO {
            get {
                return ResourceManager.GetString("CORPO_EMAIL_NOTIFICACAO_ALTERACAO_PACTO_EM_ANDAMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;b&gt;NOTIFICAÇÃO DO SISTEMA PGD&lt;/b&gt;
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///O plano de trabalho PGD {0} do servidor {1} foi assinado pela chefia e está apto a ser executado.
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Período do plano de trabalho: {2} a {3}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Atividades:
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///{4}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///O plano de trabalho deve ser assinado também pelo servidor antes de seu início.
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Para acessar o plano de trabalho clique {5}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Obrigado!
        ///
        ///Sistema PGD.
        /// </summary>
        public static string CORPO_EMAIL_NOTIFICACAO_ASSINATURA_PACTO_PELA_CHEFIA {
            get {
                return ResourceManager.GetString("CORPO_EMAIL_NOTIFICACAO_ASSINATURA_PACTO_PELA_CHEFIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;b&gt;NOTIFICAÇÃO DO SISTEMA PGD&lt;/b&gt;
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///O plano de trabalho PGD {0} do servidor {1} foi avaliado por {2}.
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Período do plano de trabalho: {3} a {4}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Data da avaliação {5}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Avaliação das Atividades:
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///
        ///{6}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Plano de trabalho {7} concluído. 
        ///
        ///Para acessar o plano de trabalho clique {8}
        ///
        ///Obrigado!
        ///
        ///Sistema PGD.
        /// </summary>
        public static string CORPO_EMAIL_NOTIFICACAO_AVALIACAO_PACTO_PELA_CHEFIA {
            get {
                return ResourceManager.GetString("CORPO_EMAIL_NOTIFICACAO_AVALIACAO_PACTO_PELA_CHEFIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;b&gt;NOTIFICAÇÃO DO SISTEMA PGD&lt;/b&gt;
        ///
        ///&lt;br&gt;&lt;br&gt;
        ///O plano de trabalho PGD {0} do servidor {1} foi avaliado parcialmente por {2}.
        ///&lt;br&gt;&lt;br&gt;
        ///
        ///Plano de trabalho avaliado parcialmente por {2}, Dirigente, na unidade {3} em {4}, às {5}, conforme horário oficial de Brasília. Foram avaliados os seguintes produtos:
        ///&lt;br&gt;&lt;br&gt;
        ///{6} da  atividade {7} totalizando {8} de carga horária na qualidade {9}
        ///&lt;br&gt;&lt;br&gt;
        ///
        ///Para acessar o plano de trabalho clique {10}
        ///&lt;br&gt;&lt;br&gt;
        ///
        ///Obrigado!
        ///&lt;br&gt;&lt;br&gt;
        ///
        ///Sistema PGD.
        /// </summary>
        public static string CORPO_EMAIL_NOTIFICACAO_AVALIACAO_PARCIAL_PACTO_PELA_CHEFIA {
            get {
                return ResourceManager.GetString("CORPO_EMAIL_NOTIFICACAO_AVALIACAO_PARCIAL_PACTO_PELA_CHEFIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;b&gt;NOTIFICAÇÃO DO SISTEMA PGD &lt;/b&gt;
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///O plano de trabalho PGD {0} do servidor {1} encerrou e requer avaliação da chefia.
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///&lt;b&gt;A não avaliação do plano de trabalho e seus produtos impedirá a criação de novos planos de trabalhos PGD para o usuário. &lt;b/&gt;
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Período do plano de trabalho: {2} a {3}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Atividades:
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///{4}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Os produtos do plano de trabalho devem ser avaliados.
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Para acessar o plano de trabalho cliqu [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string CORPO_EMAIL_NOTIFICACAO_FIM_PACTO {
            get {
                return ResourceManager.GetString("CORPO_EMAIL_NOTIFICACAO_FIM_PACTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;b&gt;NOTIFICAÇÃO DO SISTEMA PGD&lt;/b&gt;
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///O servidor {0} criou o plano de trabalho {1} que requer assinaturas para ser iniciado.
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Período do plano de trabalho: {2} a {3}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Atividades:
        ///{4}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///O plano de trabalho deve ser assinado pelo servidor e chefia antes de seu início.
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Para acessar o plano de trabalho clique {5}.
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Obrigado!
        ///
        ///Sistema PGD.
        /// </summary>
        public static string CORPO_EMAIL_NOTIFICACAO_INCLUSAO_PACTO {
            get {
                return ResourceManager.GetString("CORPO_EMAIL_NOTIFICACAO_INCLUSAO_PACTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;b&gt;NOTIFICAÇÃO DO SISTEMA PGD&lt;/b&gt;
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///O dirigente {0} criou o plano de trabalho {1} para o servidor {2} que requer assinatura para ser iniciado.
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Período do plano de trabalho: {3} a {4}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Atividades:
        ///{5}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///O plano de trabalho deve ser assinado pelo servidor e chefia antes de seu início.
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Para acessar o plano de trabalho clique {6}.
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Obrigado!
        ///
        ///Sistema PGD.
        /// </summary>
        public static string CORPO_EMAIL_NOTIFICACAO_INCLUSAO_PACTO_PELA_CHEFIA {
            get {
                return ResourceManager.GetString("CORPO_EMAIL_NOTIFICACAO_INCLUSAO_PACTO_PELA_CHEFIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;b&gt;NOTIFICAÇÃO DO SISTEMA PGD&lt;/b&gt;
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///O plano de trabalho PGD {0} do servidor {1} foi interrompido por {2}.
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Período do plano de trabalho: {3} a {4}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Data da interrupção: {5}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Motivo da interrupção: {6}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Avaliação das Atividades:
        ///{7}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Caso restem atividades deste plano de trabalho a serem executadas, deverá ser criado um novo plano de trabalho PGD.
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Plano de trabalho {8} concluído. 
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///        /// [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string CORPO_EMAIL_NOTIFICACAO_INTERRUPCAO_PACTO {
            get {
                return ResourceManager.GetString("CORPO_EMAIL_NOTIFICACAO_INTERRUPCAO_PACTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;b&gt; NOTIFICAÇÃO DO SISTEMA PGD &lt;/b&gt;
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///O plano de trabalho PGD {0} do servidor {1} foi alterado por {2} em {10}.
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///Alteração: Reativação do plano de trabalho em {10}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Período do plano de trabalho : {3} a {4}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Data da suspensão: {5}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Período do plano de trabalho após reativação: {6} a {7}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Atividades:
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///{8}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Situação do plano de trabalho: {11}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Para acessar o plano de trab [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string CORPO_EMAIL_NOTIFICACAO_PACTO_REINICIADO_APOS_SUSPENSAO {
            get {
                return ResourceManager.GetString("CORPO_EMAIL_NOTIFICACAO_PACTO_REINICIADO_APOS_SUSPENSAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;b&gt; NOTIFICAÇÃO DO SISTEMA PGD &lt;/b&gt;
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///O plano de trabalho PGD {0} do servidor {1} foi reativado automaticamente pelo sistema em {2}.
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Data da suspensão: {5}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Período do plano de trabalho após reativação: {3} a {4}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Atividades:
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///{6}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Situação do plano de trabalho: {7}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Para acessar o plano de trabalho clique {8}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Obrigado!
        ///
        ///Sistema PGD.
        /// </summary>
        public static string CORPO_EMAIL_NOTIFICACAO_PACTO_REINICIADO_AUTOMATICAMENTE {
            get {
                return ResourceManager.GetString("CORPO_EMAIL_NOTIFICACAO_PACTO_REINICIADO_AUTOMATICAMENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;b&gt;NOTIFICAÇÃO DO SISTEMA PGD&lt;/b&gt;
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///O plano de trabalho PGD {0} do servidor {1} foi suspenso por {2}.
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Período do plano de trabalho: {3} a {4}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Data da suspensão: {5}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Motivo da suspensão: {6}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Atividades:
        ///{7}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Para concluir a execução do plano de trabalho, a chefia deverá &quot;Retornar após suspensão&quot;.
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Para acessar o plano de trabalho clique {8}
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Obrigado!
        ///
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Sistema PG [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string CORPO_EMAIL_NOTIFICACAO_SUSPENSAO_PACTO {
            get {
                return ResourceManager.GetString("CORPO_EMAIL_NOTIFICACAO_SUSPENSAO_PACTO", resourceCulture);
            }
        }
    }
}
